### ISSUE TITLE
Chord sheets on my iPad opens but can't perform any operation

### ISSUE THREAD

**Issue by steve1979** [wysiwyg-software-design/chord-sheets#2]
Chord sheets on my iPad opens but can't perform any operation. I can't transpose any song, I can't export anything, I can't anymore edit anything at all the app crashes when I try to perform any operation. I have an iPad 4th gen (model ME406TY/A) with iOs 9.1. The app indicates that the current version is 3.1 and seems that I can't update to 3.2. Please help!!!

**Comment by pattrick-kreutzer** [comment]
Issues with iPad have been fixed, the update is beeing processed on the App Store and should be available within the next days.
